USE `db-todentro`;
CREATE TABLE usuario(
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(30) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(80) NOT NULL,
cargo VARCHAR(30) NULL,

PRIMARY KEY (id)
);