USE `db-todentro`;
CREATE TABLE empresa(
id INT AUTO_INCREMENT NOT NULL,
descricao VARCHAR(30) NOT NULL,
cnpj VARCHAR(20) NOT NULL,
rua VARCHAR(100) NOT NULL,
numero INT NOT NULL,
bairro VARCHAR(100) NOT NULL,
cidade VARCHAR(100) NOT NULL,
estado CHAR(2) NOT NULL,

PRIMARY KEY (id)
);
